<a href="https://colab.research.google.com/github/Sahil-Patel0630/Pytorch/blob/main/Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


Creating Tensor

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim


1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#Matrix
Matrix = torch.tensor([[7,8],[9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
Matrix.ndim

2

In [10]:
Matrix.shape

torch.Size([2, 2])

In [11]:
#Tensor
Tensor = torch.tensor([[[1,2,3],[4,5,6],[2,4,6]]])
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 4, 6]]])

In [12]:
Tensor.ndim


3

In [13]:
Tensor.shape

torch.Size([1, 3, 3])

In [14]:
Tensor_1 = torch.tensor([[[[1,2,3],[2,3,4]],[[4,5,6],[7,8,9]]]])
Tensor_1

tensor([[[[1, 2, 3],
          [2, 3, 4]],

         [[4, 5, 6],
          [7, 8, 9]]]])

In [15]:
Tensor_1.ndim

4

In [16]:
Tensor_1.shape

torch.Size([1, 2, 2, 3])

In [17]:
#Random Tensors
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7520, 0.3996, 0.1473, 0.6155],
        [0.7070, 0.3124, 0.0149, 0.3865],
        [0.2956, 0.9272, 0.3117, 0.2511]])

In [18]:
random_tensor.ndim

2

In [19]:
Random_image_size_tensor = torch.rand(size =(3,224,224))
Random_image_size_tensor.shape,Random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [20]:
#Creat a tensor of all zeros and ones
zeros = torch.zeros(size=(3,4))
Ones = torch.ones(size=(3,4))
zeros,Ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [21]:
#Creating a range of tensors and tensors
#use torch.range
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
#Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
#Tensor data type
Float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype =None,
                             device=None,
                             requires_grad=False)
Float_32_tensor.dtype

torch.float32

In [24]:
float_16_tensor=torch.tensor([3,4,5],
                             dtype=torch.float16)
float_16_tensor.dtype

torch.float16

### Manipulationg Tensors (tensor operations)
Tensor opertions include:
1.   Addition
2.   Subtraction
3.  Multiplication (Element-wise)
4.  Division
5.  Matrix Multiplication







In [25]:
tensor = torch.tensor([1,2,3])
tensor+10, tensor*10,tensor/10,tensor-10

(tensor([11, 12, 13]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]),
 tensor([-9, -8, -7]))

In [26]:
#Tryout Pytorch in-Built Function:
torch.mul(tensor,10),torch.add(tensor,10)

(tensor([10, 20, 30]), tensor([11, 12, 13]))

In [27]:
### Matrix multiplication
#Element-wise
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [28]:
#dot product
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.52 ms, sys: 103 µs, total: 1.62 ms
Wall time: 6.98 ms


tensor(14)

In [29]:
### use transpose to change shape of tensor
tensor_A= torch.tensor([[1,2],[3,4],[4,6]])
tensor_B= torch.tensor([[7,8],[9,10],[11,12]])
torch.mm(tensor_A,tensor_B.T) #torch.mm is same as torch.matmul (it's a alias for write less code)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 76,  96, 116]])

In [30]:
### Finding min, max, mean, sum etc(tensor aggregation)
x = torch.arange(0,100,10)
x.type(torch.float32).mean(), x.min(), x.max(), x.sum()

(tensor(45.), tensor(0), tensor(90), tensor(450))

In [31]:
###Finding Position of min and max value in tensor
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [32]:
from os import X_OK
###Reshaping, Staking, squeezing and un squeezing tensor
x = torch.arange(1.,13.)
x_reshaped = x.reshape(3,4)
x,x.shape, x_reshaped, x_reshaped.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]),
 tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [33]:
### changes z changes x (because a view of a tensor shares the same memory as the origional input)
z=x.view(1,12)
z,x

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [34]:
#stake tensor on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [35]:
#torch.squeez() - removes all single dimentions from target tensor
#torch.unsqueez() - add a single dimentions to target tensor at specific dim
x_reshaped.shape, x_reshaped.squeeze().shape,  x_reshaped.unsqueeze(dim = 0).shape

(torch.Size([3, 4]), torch.Size([3, 4]), torch.Size([1, 3, 4]))

In [36]:
#torch.permute - rearrange the dimention of a target tensor in a specified order
x = torch.randn(2,3,5)
y = torch.permute(x,(2,0,1))
x.size(),y.size()

(torch.Size([2, 3, 5]), torch.Size([5, 2, 3]))

In [37]:
#Indexing (selecting data from tensors)
x = torch.arange(1,10).reshape(1,3,3)
x, x[0], x[0][0], x[0][0][0]

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [38]:
#You can also use ':' to select all of a target dimention
x[:,:,1], x[:,1,1],x[0,0,:],x[0,2,2],x[:,:,2]

(tensor([[2, 5, 8]]),
 tensor([5]),
 tensor([1, 2, 3]),
 tensor(9),
 tensor([[3, 6, 9]]))

In [39]:
### Pytorch tensors and numpy
array = np.arange(1.0,8.0)
teansor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1, 2, 3]))

In [40]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [41]:
##Reproducbility (trying to take random out of random)

a = torch.rand(3,4)
b = torch.rand(3,4)
random_seed = 42
torch.manual_seed(random_seed)
random_tesnor_c = torch.rand(3,4)
torch.manual_seed(random_seed)
random_tensor_d = torch.rand(3,4)
random_tesnor_c,random_tensor_d

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [42]:
###Running tensors and Pytorch objects on the GPUs (making faster computation)
!nvidia-smi

Sun Feb 16 09:53:24 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   42C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [43]:
###check for GPU access with Pytorch
import torch
torch.cuda.is_available()

True

In [44]:
#set up device agnostic code

torch.cuda.device_count(), device

NameError: name 'device' is not defined

In [45]:
###Puting tensors (or models) on GPUs
tensor = torch.tensor([1,2,3])
print(tensor,tensor.device)


tensor([1, 2, 3]) cpu


In [46]:
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [47]:
###Moving tensors back to CPUs
#If tensor on GPU, can't transfer it to Numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [48]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu,tensor_on_gpu

(array([1, 2, 3]), tensor([1, 2, 3], device='cuda:0'))

**Exercise**

In [50]:
tensor_a = torch.rand(size=[7,7])
tensor_a

tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477],
        [0.6524, 0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331],
        [0.9578, 0.3313, 0.3227, 0.0162, 0.2137, 0.6249, 0.4340],
        [0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816]])

In [51]:
tensor_b = torch.rand(size=[1,7])
multi = torch.mm(tensor_a,tensor_b.T)
multi

tensor([[1.2748],
        [1.1652],
        [1.0182],
        [1.7959],
        [1.6076],
        [1.8623],
        [0.7118]])

In [52]:
%%time
random_seed = 0
torch.manual_seed(random_seed)
tensor_a = torch.rand(size=[7,7])
torch.manual_seed(random_seed)
tensor_b = torch.rand(size=[1,7])
multi = torch.mm(tensor_a,tensor_b.T)
multi

CPU times: user 3.58 ms, sys: 0 ns, total: 3.58 ms
Wall time: 6.52 ms


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [53]:
%%time
tensor_a = tensor_a.to(device)
tensor_b = tensor_b.to(device)
mat = torch.mm(tensor_a,tensor_b.T)
mat

CPU times: user 21.7 ms, sys: 10.8 ms, total: 32.5 ms
Wall time: 128 ms


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]], device='cuda:0')

In [54]:
random_seed = 1234
torch.manual_seed(random_seed)
tensor_1= torch.rand([2,3])
torch.manual_seed(random_seed)
tensor_2= torch.rand([2,3])
mul = torch.mm(tensor_1,tensor_2.T)
tensor_1, tensor_2,mul

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.2299, 0.2161],
         [0.2161, 0.6287]]))

In [55]:
max = mul.max()
min = mul.min()
max,min

(tensor(0.6287), tensor(0.2161))

In [56]:
tensor = torch.rand([1,1,1,10])
y =tensor.squeeze()
tensor, y

(tensor([[[[0.0518, 0.4681, 0.6738, 0.3315, 0.7837, 0.5631, 0.7749, 0.8208,
            0.2793, 0.6817]]]]),
 tensor([0.0518, 0.4681, 0.6738, 0.3315, 0.7837, 0.5631, 0.7749, 0.8208, 0.2793,
         0.6817]))

In [57]:
rendom_seed = 7
torch.manual_seed(rendom_seed)
tensor = torch.rand([1,1,1,10])
Y = tensor.squeeze()
tensor,tensor.shape,Y,Y.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))